name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.5'

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o ../../netdac.exe .
        working-directory: ./cmd/netdac/

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o ../../netdac .
        working-directory: ./cmd/netdac/

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            netdac.exe
            netdac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
